spring.datasource.url=jdbc:postgresql://dpg-d61bfv15pdvs7363aag-a:5432/fantasy_lol_db_hbxj
spring.datasource.username=fantasy_lol_db_hbxj_user
spring.datasource.password=TU_PASSWORD

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}
jwt.secret=TU_SECRETO_JWT
jwt.expiration=3600000