spring.datasource.url=jdbc:postgresql://dpg-d6lbfv15pdvs73f63aag-a.frankfurt-postgres.render.com:5432/fantasy_lol_db_hbxj
spring.datasource.username=fantasy_lol_db_hbxj_user
spring.datasource.password=Wr19Y3BnWyJ6e4gaPk81xr6oGfXQV3RT

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

jwt.secret=mi_super_clave_jwt_ultra_segura_2026_fantasy_lol_api_render
jwt.expiration=3600000

pandascore.base.url=https://api.pandascore.co
pandascore.api.key=Cbg1MQPiBY07iDCjloRzgFqjbEzlhfTg0w74IP6BsJXcu620Pac